version: ~> 1.0
os: linux
dist: focal
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - docker pull fr3akyphantom/droid-builder:focal
before_script:
  - cd $HOME && mkdir twrp
  - TWRP_SOURCE1="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-8.1-norepo-20210130.tzst.aa" && TWRP_SOURCE2="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-8.1-norepo-20210130.tzst.ab" && TWRP_SOURCE3="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-8.1-norepo-20210130.tzst.ac"
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE1}" || wget -q --show-progress --progress=bar:force "${TWRP_SOURCE1}"
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE2}" || wget -q --show-progress --progress=bar:force "${TWRP_SOURCE2}"
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE3}" || wget -q --show-progress --progress=bar:force "${TWRP_SOURCE3}"
  - cat MinimalOmniRecovery-twrp-*.*-norepo-2021*.tzst.ab MinimalOmniRecovery-twrp-*.*-norepo-2021*.tzst.ac >> MinimalOmniRecovery-twrp-*.*-norepo-2021*.tzst.aa
  - tar --zstd -xf MinimalOmniRecovery-twrp-*.*-norepo-2021*.tzst.aa --directory $HOME/twrp/ && rm MinimalOmniRecovery*.tzst.*
script:
  - cd $HOME/twrp/ && git clone https://github.com/AlienNetworks/android_device_MStar_VDPG.git device/MStar/sugarcane
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-8.1 --depth 1 bootable/recovery
  - |
    sudo chown -R travis:docker $HOME/twrp
    docker run --privileged --rm -i -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw" fr3akyphantom/droid-builder:focal bash << EOF
    cd /home/builder/twrp/
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
    BUILD_FLAVOR="userdebug"
    lunch omni_sugarcane-${BUILD_FLAVOR}
    make -j$(nproc --all) recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/sugarcane/recovery.img $HOME/twrp/TWRP-$version-sugarcane-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-sugarcane-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    repo: AlienNetworks/android_device_MStar_VDPG # Optional: If you want to deploy on different repository
    branch: main # Optional: Needs to be exact as the config branch
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
