os: linux
dist: bionic
addons:
  apt:
    packages:
    - git-core
    - gnupg
    - flex
    - bison
    - build-essential
    - zip
    - curl
    - zlib1g-dev
    - gcc-multilib
    - g++-multilib
    - libc6-dev-i386
    - libncurses5-dev
    - lib32ncurses5-dev
    - x11proto-core-dev
    - libx11-dev
    - lib32z1-dev
    - libgl1-mesa-dev
    - libxml2-utils
    - xsltproc
    - unzip
    - fontconfig
    - openjdk-8-jdk
    - python
language: shell
git:
  depth: 1
  quiet: true
before_install:
  - mkdir -p ~/.bin && PATH="${HOME}/.bin:${PATH}" && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo && chmod a+rx ~/.bin/repo && mkdir -p ~/twrp && mkdir -p ~/.ccache && cd ~/twrp
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
  - mkdir ~/twrp/.repo/local_manifests
  - echo '<manifest>' >> ~/twrp/.repo/local_manifests/local_manifest.xml
  - echo '    <project path="device/MStar/sugarcane" name="AlienNetworks/android_device_MStar_VDPG" remote="github" revision="main" />' >> ~/twrp/.repo/local_manifests/local_manifest.xml
  - echo '</manifest>' >> ~/twrp/.repo/local_manifests/local_manifest.xml
  - repo sync
before_script:
  - export LC_ALL=C 
  - export ALLOW_MISSING_DEPENDENCIES=true
  - source build/envsetup.sh
  - lunch omni_sugarcane-userdebug
script:
  - mka recoveryimage
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/sugarcane/recovery.img $HOME/twrp/TWRP-$version-sugarcane-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
deploy:
  provider: releases
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: true # Set "true" to deploy only on successful tagged commit builds
    repo: AlienNetworks/android_device_MStar_VDPG # Optional: If you want to deploy on different repository
    branch: main # Optional: Needs to be exact as the config branch
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
